name: Deploy Lambda Function
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # TODO: Change to your AWS region

    - name: Zip Lambda function
      run: Compress-Archive -Path lambda_function.py -DestinationPath function.zip -Force

    - name: Deploy to Lambda
      run: aws lambda update-function-code --function-name value3 --zip-file fileb://function.zip
