name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "build job"
  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run a one-line script
      run: echo "test job"